#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

# module add seas-anaconda3
# conda activate chenyehu

SEED=$1
C=$2
n=$3
m=$4
horizon=$5
TYPE=$6

# Rscript --vanilla generate_data.R $SEED $C $n $m $horizon 'GP'
# Rscript --vanilla 2PL.R $SEED $C $n $m $horizon 'GP'
Rscript --vanilla gpirt-sdo.R $SEED $C $n $m $horizon $TYPE
# Rscript --vanilla bgrm_logit.R $SEED $C $n $m 'GP'
Rscript --vanilla evaluate.R $SEED $C $n $m $horizon $TYPE

# conda deactivate