#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

# module add R-4
# module add gcc-8.3.0

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

# module add seas-anaconda3
# conda activate chenyehu

TSY=$1
TEY=$2
TY=$3
SEED=$4
TYPE=$5

if [ $TYPE = "GPIRT" ]
then
    Rscript --vanilla gpirt_SupremeCourt_holdout.R $TSY $TEY $TY $SEED "Matern"
elif [ $TYPE = "SEIRT" ]; then
    Rscript --vanilla gpirt_SupremeCourt_holdout.R $TSY $TEY $TY $SEED "RBF"
elif [ $TYPE = "DSEM" ]; then
    Rscript --vanilla ./utils/DSEM_SupremeCourt_holdout.R $TSY $TEY $TY $SEED $TYPE
elif [[ $TYPE =~ "_" ]]; then
    Rscript --vanilla ./utils/MIRT_SupremeCourt_holdout.R $TSY $TEY $TY $SEED $TYPE
else
    Rscript --vanilla doirt_SupremeCourt_holdout.R $TSY $TEY $TY $SEED
fi

# conda deactivate