#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

# module add R-4
# module add gcc-8.3.0

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

# module add seas-anaconda3
# conda activate chenyehu

TSY=$1
TEY=$2
TY=$3

Rscript --vanilla gpirt_CIRI_hold_out.R $TSY $TEY $TY
# Rscript --vanilla doirt_CIRI_hold_out.R $TSY $TEY $TY

# conda deactivate