#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

# module add seas-anaconda3
# conda activate chenyehu

SEED=$1
C=$2
n=$3
m=$4

cmd1="Rscript --vanilla generate_data.R $SEED $C $n $m 'GP'"
cmd2="Rscript --vanilla gpirt-sdo.R $SEED $C $n $m 'GP'"
cmd1 && cmd2

# conda deactivate