#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

module add seas-anaconda3
conda activate chenyehu

SEED=$1
C=$2
n=$3
m=$4

Rscript --vanilla gpirt-sdo.R $SEED $C $n $m "GP"

conda deactivate