#!/bin/bash

mkdir -p data
mkdir -p figures
mkdir -p results

MAXSEED=100
declare -a Cs=(2)
declare -a ns=(100)
declare -a ms=(50)
horizon=10
declare -a TYPES=("GP" "CST" "RDM")
declare -a TYPES=("GP")

if [ $1 = "run" ]
then
    for TYPE in ${TYPES[@]}; do
        for SEED in $(seq 1 1 $MAXSEED); do
            for C in ${Cs[@]}; do
                for n in ${ns[@]}; do
                    for m in ${ms[@]}; do
                        bsub -G SEAS-Lab-Garnett -J "${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}" -o "./log/${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}.log" "./onerun $SEED $C $n $m $horizon ${TYPE}"
                    done
                done
            done
        done
    done
elif [ $1 = "compare" ]
then
    for C in ${Cs[@]}; do
        for n in ${ns[@]}; do
            for m in ${ms[@]}; do
                Rscript --vanilla compare.R $MAXSEED $C $n $m $horizon 'GP'
            done
        done
    done
fi
