#!/bin/bash

mkdir -p data
mkdir -p figures
mkdir -p results
mkdir -p log

MAXSEED=25
declare -a Cs=(2 5)
declare -a ns=(100)
# declare -a ms=(10)
horizon=10
m=10
DATA_TYPE="GP"
declare -a TYPES=("GP" "CST" "RDM" "BRW")
declare -a CONSTANT_IRFs=(0)
declare -a TYPES=("DSEM" "graded_uni" "gpcm_uni" "sequential_uni" "ggum_uni")

if [ $1 = "run" ]
then
    for TYPE in ${TYPES[@]}; do
        for SEED in $(seq 1 1 $MAXSEED); do
            for C in ${Cs[@]}; do
                for n in ${ns[@]}; do
                    for CONSTANT_IRF in ${CONSTANT_IRFs[@]}; do
                        # if [ $m -eq 10 ]; then
                        #     CONSTANT_IRF=1
                        # else
                        #     CONSTANT_IRF=0
                        # fi
                        bsub -G SEAS-Lab-Garnett -J "${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}" -o "./log/${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}.log" "./onerun $SEED $C $n $m $horizon ${TYPE} ${CONSTANT_IRF} ${DATA_TYPE}"
                    done
                done
            done
        done
    done
elif [ $1 = "compare" ]
then
    for C in ${Cs[@]}; do
        for n in ${ns[@]}; do
            for CONSTANT_IRF in ${CONSTANT_IRFs[@]}; do
                # if [ $m -eq 10 ]; then
                #     CONSTANT_IRF=1
                # else
                #     CONSTANT_IRF=0
                # fi
                Rscript --vanilla compare.R $MAXSEED $C $n $m $horizon 'GP' ${CONSTANT_IRF}
            done
        done
    done
elif [ $1 = "rebuttal" ]
then 
    n=100
    SEED=1
    declare -a TYPES=("GP" "CST" "RDM" "BRW")
    declare -a CONSTANT_IRFs=(0 1)
    declare -a DATA_TYPES=("2PL" "Wiener")
    declare -a TYPES=("BRW")
    declare -a CONSTANT_IRFs=(0)
    
    for DATA_TYPE in ${DATA_TYPES[@]}; do
        for TYPE in ${TYPES[@]}; do
            for C in ${Cs[@]}; do
                for CONSTANT_IRF in ${CONSTANT_IRFs[@]}; do
                    bsub -G SEAS-Lab-Garnett -J "${DATA_TYPE}_${TYPE}_C${C}_CSTIRF${CONSTANT_IRF}_${SEED}" -o "./log/${DATA_TYPE}_${TYPE}_C${C}_CSTIRF${CONSTANT_IRF}_${SEED}.log" "./onerun $SEED $C $n $m $horizon ${TYPE} ${CONSTANT_IRF} ${DATA_TYPE}"
                done
            done
        done
    done
fi
