#!/bin/bash

mkdir -p data
mkdir -p figures
mkdir -p results
mkdir -p log

MAXSEED=25
declare -a Cs=(2 5)
declare -a ns=(50)
declare -a ms=(10)
horizon=10
m=10
declare -a TYPES=("GP" "CST" "RDM" "BRW")
declare -a CONSTANT_IRFs=(0 1)
declare -a TYPES=("GP")

if [ $1 = "run" ]
then
    for TYPE in ${TYPES[@]}; do
        for SEED in $(seq 1 1 $MAXSEED); do
            for C in ${Cs[@]}; do
                for n in ${ns[@]}; do
                    for CONSTANT_IRF in ${CONSTANT_IRFs[@]}; do
                        # if [ $m -eq 10 ]; then
                        #     CONSTANT_IRF=1
                        # else
                        #     CONSTANT_IRF=0
                        # fi
                        bsub -G SEAS-Lab-Garnett -J "${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}" -o "./log/${TYPE}_C${C}n${n}m${m}h${horizon}_${SEED}.log" "./onerun $SEED $C $n $m $horizon ${TYPE} ${CONSTANT_IRF}"
                    done
                done
            done
        done
    done
elif [ $1 = "compare" ]
then
    for C in ${Cs[@]}; do
        for n in ${ns[@]}; do
            for CONSTANT_IRF in ${CONSTANT_IRFs[@]}; do
                # if [ $m -eq 10 ]; then
                #     CONSTANT_IRF=1
                # else
                #     CONSTANT_IRF=0
                # fi
                Rscript --vanilla compare.R $MAXSEED $C $n $m $horizon 'GP' ${CONSTANT_IRF}
            done
        done
    done
fi
