#!/bin/bash

mkdir -p data
mkdir -p figures
mkdir -p results
mkdir -p log

TSY=2000
TEY=2015
TY=2020
MAXSEED=25
NODE4="node04.engr.wustl.edu"
declare -a TYPES=("SEIRT" "DOIRT")
declare -a TYPES=("DSEM" "graded_uni" "gpcm_uni" "sequential_uni" "ggum_uni")

if [[ $1 == "run" ]]
then
    for TYPE in ${TYPES[@]}; do
        for SEED in $(seq 1 1 $MAXSEED); do
            # -G SEAS-Lab-Garnett
            bsub -J "${TYPE}_${SEED}" -o "./log/${TYPE}_${SEED}.log" -R "hname!=${NODE4}" "./onerun_holdout $TSY $TEY $TY $SEED $TYPE"
        done
    done
elif [[ $1 == "compare" ]]
then
    Rscript --vanilla compare_holdout.R $TSY $TEY $TY $MAXSEED 'SupremeCourt'
fi
