#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

# module add R-4
# module add gcc-8.3.0

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu

# module add seas-anaconda3
# conda activate chenyehu

TSY=$1
TEY=$2
TY=$3
SEED=$4
TYPE=$5
DR=$6

if [ $TYPE = "GPIRT" ]
then
    Rscript --vanilla gpirt_TAPS_holdout.R $TSY $TEY $TY $SEED $DR "Matern"
elif [ $TYPE = "SEIRT" ]; then
    Rscript --vanilla gpirt_TAPS_holdout.R $TSY $TEY $TY $SEED $DR "RBF"
elif [ $TYPE = "NIRT" ]; then
    Rscript --vanilla gpirt_TAPS_holdout.R $TSY $TEY $TY $SEED $DR "NIRT"
elif [ $TYPE = "LIRT" ]; then
    Rscript --vanilla gpirt_TAPS_holdout.R $TSY $TEY $TY $SEED $DR "LIRT"
elif [ $TYPE = "DSEM" ]; then
    Rscript --vanilla DSEM_TAPS_holdout.R $TSY $TEY $TY $SEED $DR $TYPE
elif [[ $TYPE =~ "_" ]]; then
    Rscript --vanilla MIRT_TAPS_holdout.R $TSY $TEY $TY $SEED $DR $TYPE
else
    Rscript --vanilla doirt_TAPS.R $TSY $TEY $TY $SEED $DR
fi

# conda deactivate